[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Skoda"
Model = "Octavia iV"
Name = "Skoda"
SerialNumber = "AA:AA:AA:AA:AA:CC"
FirmwareRevision = "100.1.1"


[[services]]
type = "BatteryService"

[services.characteristics]
Name = "Akku"
[services.characteristics.BatteryLevel]
polling = 300
cmd = "cd skoda; ./cmd/batteryPercentage.sh"
[services.characteristics.ChargingState]
polling = 30
cmd = "cd skoda; ./cmd/charge.sh"
[services.characteristics.StatusLowBattery]
polling = 300
cmd = "cd skoda; test \"$(./cmd/batteryPercentage.sh)\" -lt 50 && echo 1 || echo 0"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Lataus"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/charge.sh"



[[services]]
type = "Switch"

[services.characteristics]
Name = "Ilmastointi"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/clima.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Ikkunalämmitys"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/windowHeating.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Latausaikaa jäljellä (s)"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/secondsRemainingToCharge.sh"
polling = 300
MaxValue = 36000


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Lämmitysaikaa jäljellä sekuntia"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/secondsRemainingToHeat.sh"
polling = 60
maxValue = 7200


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Tarvittava latausaika tuntia"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/hoursNeededToCharge.sh 13"
