bridge = "skoda"
port = 12305
username = "AA:AA:AA:AA:AA:05"

[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Skoda"
Model = "Octavia iV"
Name = "Skoda"
SerialNumber = "AA:AA:AA:AA:AA:05"
FirmwareRevision = "100.1.1"


[[services]]
type = "BatteryService"

[services.characteristics]
Name = "Akku"
[services.characteristics.BatteryLevel]
cmd = "cd skoda; ./cmd/batteryPercentage.sh"
[services.characteristics.ChargingState]
cmd = "cd skoda; ./cmd/charge.sh"
[services.characteristics.StatusLowBattery]
cmd = "cd skoda; ./cmd/lowBattery.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Lataus"
ConfiguredName = "Lataus"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/charge.sh"



[[services]]
type = "Switch"

[services.characteristics]
Name = "Ilmastointi"
ConfiguredName = "Ilmastointi"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/clima.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Ikkunalämmitys"
ConfiguredName = "Ikkunalämmitys"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/windowHeating.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Latausaikaa jäljellä (s)"
ConfiguredName = "Latausaikaa jäljellä (s)"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/secondsRemainingToCharge.sh"
maxValue = 36000


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Lämmitysaikaa jäljellä sekuntia"
ConfiguredName = "Lämmitysaikaa jäljellä sekuntia"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/secondsRemainingToHeat.sh"
maxValue = 7200


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Tarvittava latausaika tuntia"
ConfiguredName = "Tarvittava latausaika tuntia"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/hoursNeededToCharge.sh 13"
