[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Skoda"
Model = "Octavia iV"
Name = "Auto"
SerialNumber = "AA:AA:AA:AA:AA:CC"
FirmwareRevision = "100.1.1"


[[services]]
type = "BatteryService"
#polling = 60

[services.characteristics]
Name = "Akku"
ChargingState = 0
StatusLowBattery = 0
[services.characteristics.BatteryLevel]
cmd = "cd skoda; ./cmd/batteryPercentage.sh"
value = 0


[[services]]
type = "Switch"

[services.characteristics]
Name = "Lataus"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/charge.sh"
value = false



[[services]]
type = "Switch"

[services.characteristics]
Name = "Ilmastointi"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/clima.sh"
value = false


[[services]]
type = "Switch"

[services.characteristics]
Name = "Ikkunalämmitys"
[services.characteristics.On]
cmd = "cd skoda; ./cmd/windowHeating.sh"
value = false


[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Latausaikaa jäljellä (s)"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/secondsRemainingToCharge.sh"
value = 0


[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Lämmitysaikaa jäljellä sekuntia"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/secondsRemainingToHeat.sh"
value = 0



[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Tarvittava latausaika tuntia"
[services.characteristics.CurrentTemperature]
cmd = "cd skoda; ./cmd/hoursNeededToCharge.sh 13"
value = 0
